---
- name: Change default shell to zsh
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh

- name: Create zsh history file
  file:
    path: "{{ user_home }}/.zsh_history"
    state: touch
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0600'
  args:
    creates: "{{ user_home }}/.zsh_history"
